# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.anova_test_cpp <- function(treatment, response, K, alpha) {
    .Call('_restricted_anova_test', PACKAGE = 'restricted', treatment, response, K, alpha)
}

.anova_test_per_subject_cpp <- function(treatment_list, response_list, K, alpha, time_drift) {
    .Call('_restricted_anova_test_per_subject', PACKAGE = 'restricted', treatment_list, response_list, K, alpha, time_drift)
}

.restricted_one_simulation_cpp <- function(w, nsbj, procedure, parameter) {
    .Call('_restricted_restricted_one_simulation', PACKAGE = 'restricted', w, nsbj, procedure, parameter)
}

.restricted_multiple_simulations_cpp <- function(w, nsbj, procedure, parameter, nsim) {
    .Call('_restricted_restricted_multiple_simulations', PACKAGE = 'restricted', w, nsbj, procedure, parameter, nsim)
}

